### ISSUE TITLE
want to know about the rel the directory 

### ISSUE THREAD

**Issue by siddhant3030** [erikknaake/DockerizePhoenix#1]
hi, 

I'm trying your example dockerizing elixir project. I was confused about the rel folder can you give some insights on that.

**Comment by erikknaake** [comment]
I don't know too much about the rel folder, but it is a folder generated by `mix release.init`. The folder contains configuration for the platform (.sh for linux and .bat for windows)

The following is an example of the `env.sh.eex` file I use for another dockerized Elixir application
```sh
CONTAINER_IP=$(hostname -i)
echo "ip: $CONTAINER_IP , name will be: phoenix@$CONTAINER_IP"
export RELEASE_DISTRIBUTION=name
export RELEASE_NODE="phoenix@${CONTAINER_IP}"
```
The `vm.args.eex` can be used to tweak BeamVM settings. 

The files in the rel folder are only used when you run your application via a release, i.e. not with mix phx.server or simular.

Those scripts run before your application starts
